# Generated by Django 5.1.4 on 2024-12-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('lot_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_utility', models.BooleanField(default=False)),
                ('is_social', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
