# Generated by Django 5.1.4 on 2024-12-10 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_incidents_payments_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
